= Development environment

* Java 11
* Docker >= 19.03
* IntelliJ IDEA with Kotlin 1.3

== Executing tests

Tests can be triggered from IntelliJ or with gradle:

```bash
./gradlew test
```

== Running the application

The simplest way to run the application is by executing the `main` function from IntelliJ.
The `main` function can be found in the `Application` class.

The application can also be run in command line with gradle:

```bash
./gradlew run
```

The port number and configuration can be optionally passed as arguments:

```bash
./gradlew run --args 'classpath:in-memory.properties 9090'
```

A custom configuration file can also be loaded with:

```bash
./gradlew run --args 'path/to/my.properties'
```

There are two persistence strategies to choose from to run the application:

* in-memory (default) - `classpath:in-memory.properties`
* postgresql - `classpath:postgresql.properties`

A running postgresql server is needed for the `postgresql` strategy.
It can be started with the provided `docker-compose` configuration:

```bash
docker-compose up -d
```

== Building the application jar

To build a fat jar with all the necessary dependencies run:

```bash
./gradlew shadowJar
```

Now the jar can be executed with:

```bash
java -jar build/libs/mastermind-1.0-SNAPSHOT.jar
```

Arguments can be provided as well:

```bash
java -jar build/libs/mastermind-1.0-SNAPSHOT.jar classpath:postgresql.properties 9090
```